$( function() {
    var availableTags = [
    "Aston Martin",
    "Audi",
    "Bajaj",
    "Bentley",
    "Bmw",
    "Bugatti",
    "Datsun",
    "Dc",
    "Ferrari",
    "Fiat",
    "Force",
    "Ford",
    "Honda",
    "Hyundai",
    "Icml",
    "Isuzu",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini",
    "Land Rover",
    "Land Rover Rover",
    "Lexus",
    "Mahindra",
    "Maruti Suzuki",
    "Maruti Suzuki R",
    "Maserati",
    "Mg",
    "Mini",
    "Mitsubishi",
    "Nissan",
    "Porsche",
    "Premier",
    "Renault",
    "Skoda",
    "Tata",
    "Toyota",
    "Volkswagen",
    "Volvo"
    ];
    $( "#abc" ).autocomplete({
      source: availableTags
    });
  } );
  $( function() {
    var availableTags = [
    "Db 11",
    "Vantage",
    "Rapide",
    "A3",
    "Q3",
    "A4",
    "A3 Cabriolet",
    "A6",
    "S5",
    "Rs5",
    "Q8",
    "A8 L",
    "R8",
    "Q5",
    "Q7",
    "Rs7",
    "A5 Cabriolet",
    "A5",
    "Qute (Re60)",
    "Continental Gt",
    "Bentayga",
    "Mulsanne",
    "Flying Spur",
    "X3",
    "X5",
    "M2 Competition",
    "7-Series",
    "X1",
    "3-Series",
    "X4",
    "Z4 Roadster",
    "X7",
    "M4",
    "5-Series",
    "6-Series",
    "M5",
    "Chiron",
    "Redi-Go",
    "Go",
    "Avanti",
    "Portofino",
    "458 Speciale",
    "488 Gtb",
    "Gtc4 Lusso",
    "812 Superfast",
    "458 Spider",
    "Urban Cross",
    "Avventura",
    "Linea",
    "Abarth Avventura",
    "Punto Evo Pure",
    "Linea Classic",
    "Abarth Punto",
    "Punto Evo",
    "Gurkha",
    "Freestyle",
    "Aspire",
    "Mustang",
    "Ecosport",
    "Endeavour",
    "Figo",
    "Jazz",
    "Cr-V",
    "Amaze",
    "Brv",
    "Civic",
    "Wr-V",
    "Accord Hybrid",
    "City",
    "Santro",
    "Xcent Prime",
    "Elite I20",
    "Aura",
    "Grand I10 Prime",
    "Venue",
    "I20 Active",
    "Verna",
    "Grand I10",
    "Elantra",
    "Tucson",
    "Grand I10 Nios",
    "Xcent",
    "Creta",
    "Kona Electric",
    "Extreme",
    "Mu-X",
    "Dmax V-Cross",
    "Xe",
    "Xf",
    "Xj",
    "F-Pace",
    "F-Type",
    "Compass Trailhawk",
    "Grand Cherokee",
    "Compass",
    "Wrangler",
    "Carnival",
    "Seltos",
    "Urus",
    "Huracan",
    "Aventador",
    "Discovery Sport",
    "Discovery",
    "Evoque",
    "Evoque Convertible",
    "Velar",
    "Sport",
    "Rx 450H",
    "Lc 500H",
    "Lx 450D",
    "Es",
    "Nx 300H",
    "Lx 570",
    "Ls 500H",
    "Verito Vibe",
    "Alturas G4",
    "Kuv100 Nxt",
    "Bolero Power Plus",
    "Xuv300",
    "E2O Plus",
    "Thar",
    "Tuv300 Plus",
    "Marazzo",
    "Scorpio",
    "Xuv500",
    "E Verito",
    "Tuv300",
    "Xylo",
    "Bolero",
    "Nuvosport",
    "Verito",
    "Eeco",
    "Alto K10",
    "Celerio Tour",
    "Celerio X",
    "Ignis",
    "Dzire Tour",
    "Dzire",
    "Alto",
    "S-Presso",
    "Celerio",
    "Swift",
    "Gypsy",
    "Vitara Brezza",
    "Xl6",
    "Omni",
    "Baleno",
    "Ertiga",
    "Baleno Rs",
    "S-Cross",
    "Alto 800 Tour",
    "Ciaz",
    "Wagon",
    "Levante",
    "Granturismo",
    "Quattroporte",
    "Ghibli",
    "Grancabrio",
    "Zs Ev",
    "Hector",
    "Cooper 5 Door",
    "Convertible",
    "Clubman",
    "John Cooper Works",
    "Cooper 3 Door",
    "Countryman",
    "Outlander",
    "Pajero Sport",
    "Montero",
    "Micra Active",
    "Sunny",
    "Terrano",
    "Gtr",
    "Micra",
    "Kicks",
    "718",
    "Panamera",
    "Cayenne",
    "911",
    "Macan",
    "Cayenne Coupe",
    "Rio",
    "Kwid",
    "Triber",
    "Duster",
    "Lodgy",
    "Captur",
    "Superb Sportline",
    "Kodiaq",
    "Monte Carlo",
    "Superb",
    "Kodiaq Scout",
    "Rapid",
    "Octavia",
    "Nano Genx",
    "Tiago",
    "Bolt",
    "Altroz",
    "Tigor",
    "Zest",
    "Nexon",
    "Tigor Ev",
    "Hexa",
    "Safari Storme",
    "Nexon Ev",
    "Harrier",
    "Tiago Nrg",
    "Winger",
    "Etios Liva",
    "Platinum Etios",
    "Etios Cross",
    "Glanza",
    "Land Cruiser Prado",
    "Innova Crysta",
    "Corolla Altis",
    "Fortuner",
    "Land Cruiser",
    "Prius",
    "Camry",
    "Yaris",
    "Polo",
    "Ameo",
    "Tiguan",
    "Vento",
    "Passat",
    "Xc40",
    "S90",
    "V40",
    "S60",
    "S60 Cross Country",
    "Xc60",
    "Xc90",
    "V40 Cross Country",
    "V90 Cross Country",
    "Mercedes-Benz B-Class",
    "Mercedes-Benz Cla-Class",
    "Mercedes-Benz E-Class Cabriolet",
    "Mercedes-Benz Gls",
    "Mercedes-Benz S-Class",
    "Mercedes-Benz G-Class",
    "Mercedes-Benz Maybach",
    "Mercedes-Benz S-Class Cabriolet",
    "Rolls-Royce Ghost Series Ii",
    "Rolls-Royce Wraith",
    "Rolls-Royce Cullinan",
    "Rolls-Royce Phantom Coupe",
    "Mercedes-Benz E-Class",
    "Mercedes-Benz C-Class Cabriolet",
    "Mercedes-Benz V-Class",
    "Mercedes-Benz E-Class All Terrain",
    "Mercedes-Benz Amg-Gt",
    "Mercedes-Benz Amg Gt 4-Door Coupe",
    "Rolls-Royce Dawn",
    "Rolls-Royce Drophead Coupe",
    "Go+",
    "Mercedes-Benz A-Class",
    "Mercedes-Benz C-Class",
    "Mercedes-Benz Gle",
    "Mercedes-Benz Cls",
    "Mercedes-Benz Gla-Class",
    "Rolls-Royce Phantom",
    "Mercedes-Benz Glc"
    ];
    $( "#abc1" ).autocomplete({
      source: availableTags
    });
  } );
  $( function() {
    var availableTags = [
    "V12",
    "Coupe",
    "Luxe",
    "35 Tdi Premium Plus",
    "35 Tdi Technology",
    "35 Tfsi Premium Plus",
    "35 Tfsi Technology",
    "30 Tdi Premium Fwd",
    "35 Tdi Quattro Premium Plus",
    "35 Tdi Quattro Technology",
    "30 Tfsi Premium",
    "Premium Plus 35 Tfsi",
    "Technology 35 Tfsi",
    "40 Tfsi",
    "Premium Plus 45 Tfsi",
    "Technology 45 Tfsi",
    "Sportback",
    "55 Tfsi Quattro Tiptronic",
    "55 Tfsi Quattro",
    "V10 Plus",
    "45 Tfsi Premium Plus",
    "45 Tfsi Technology",
    "45 Tdi Premium Plus",
    "45 Tdi Technology Pack",
    "40 Tfsi Quattro Premium Plus",
    "40 Tfsi Quattro Technology Pack",
    "45 Tdi Black Styling",
    "40 Tfsi Quattro Black Styling",
    "2.0 Tdi",
    "Qcar",
    "Qcar Cng",
    "W12",
    "V8",
    "Sedan",
    "Xdrive 20D Luxury Line",
    "Xdrive 30I Luxury Line",
    "Xdrive20D Xline",
    "Xdrive30D Sport",
    "Xdrive30D Xline",
    "Xdrive40I M Sport",
    "730Ld Design Pure Excellence",
    "730Ld Design Pure Excellence Signature",
    "730Ld M Sport",
    "740Li Design Pure Excellence Signature",
    "745Le Xdrive",
    "M760Li Xdrive",
    "Sdrive20D Expedition",
    "Sdrive20D Xline",
    "Xdrive20D M Sport",
    "Sdrive20D M Sport",
    "Sdrive20I Xline",
    "320D Sport",
    "320D Luxury Line",
    "330I M Sport",
    "Xdrive20D M Sport X",
    "Xdrive30D M Sport X",
    "Xdrive30I M Sport X",
    "Sdrive 20I",
    "M 40I",
    "Xdrive 40I",
    "Xdrive30D Dpe Signature",
    "520D Luxury Line",
    "530D M Sport",
    "530I M Sport",
    "630D Gt Luxury Line",
    "630D Gt M Sport",
    "630I Gt Luxury Line",
    "620D Gt Luxury Line",
    "Competition",
    "W16",
    "Sport",
    "D",
    "T",
    "A",
    "S",
    "1.0 S",
    "1.0 S Amt",
    "T (O)",
    "A (O)",
    "T Vdc",
    "T (O) Vdc",
    "T Cvt",
    "T (O) Cvt",
    "Standard",
    "V8 Convertible",
    "Std",
    "Spider",
    "V8 T",
    "Superfast",
    "1.3 Multijet Active",
    "1.3 Multijet Dynamic",
    "1.4 T-Jet Emotion",
    "1.3 Multijet Emotion",
    "Multijet Dynamic",
    "Multijet Active",
    "Multijet Emotion",
    "Active Fire",
    "Active Multijet",
    "Dynamic Multijet",
    "Emotion Multijet",
    "T-Jet Emotion",
    "1.4 T-Jet",
    "1.2L Fire Dynamic",
    "1.3",
    "1.3 Multijet",
    "1.4",
    "Plus 1.3 Multijet",
    "Dynamic 1.2",
    "Active Multijet 1.3",
    "Dynamic Multijet 1.3",
    "Emotion Multijet 1.3",
    "Xpedition 5 Door",
    "Xplorer 3 Door",
    "Xtreme",
    "Xtreme Abs",
    "Xpedition 3 Door",
    "Xplorer 5 Door",
    "1.5L Tdci Ambiente",
    "1.5L Tdci Titanium",
    "1.5L Tdci Titanium Plus",
    "1.2L Ti-Vct Ambiente",
    "1.2L Ti-Vct Titanium",
    "1.2L Ti-Vct Titanium Plus",
    "1.2L Ti-Vct Trend Plus",
    "1.5L Tdci Trend Plus",
    "1.2 Ti-Vct Ambiente",
    "1.2 Ti-Vct Trend Plus",
    "1.2 Ti-Vct Trend",
    "1.5 Tdci Ambiente",
    "1.5 Tdci Trend",
    "1.5 Tdci Trend Plus",
    "1.5 Tdci Titanium",
    "1.5 Tdci Titanium Plus",
    "1.2 Ti-Vct Titanium Plus",
    "1.2 Ti-Vct Titanium",
    "1.2 Trend Plus Cng",
    "1.2 Ti-Vct Blu",
    "1.5 Tdci Blu",
    "Fastback V8",
    "1.5L Ti-Vct Ambiente",
    "1.5L Ti-Vct Trend",
    "1.5L Ti-Vct Titanium",
    "1.5L Ti-Vct Titanium Plus At",
    "1.5L Tdci Trend",
    "1.5L Ti-Vct Titanium Plus",
    "1.5L Tdci Titanium S",
    "1.5L Ti-Vct Thunder Edition",
    "1.5L Tdci Thunder Edition",
    "3.2L 4X4 At Titanium Plus",
    "2.2L 4X2 At Titanium Plus",
    "2.2L 4X2 Mt Titanium",
    "Ambiente 1.2 Ti-Vct",
    "Ambiente 1.5 Tdci",
    "Titanium 1.2 Ti-Vct",
    "Titanium1.5 Tdci",
    "Titanium Blu 1.2 Ti-Vct",
    "Titanium Blu 1.5 Tdci",
    "V Petrol",
    "Vx Cvt",
    "Vx Petrol",
    "V Cvt",
    "S Diesel",
    "V Diesel",
    "Vx Diesel",
    "Exclusive Edition Cvt",
    "2Wd Petrol Cvt",
    "2Wd Diesel At",
    "Awd Diesel At",
    "S Cvt Petrol",
    "E Mt Diesel",
    "E Mt Petrol",
    "S Cvt Diesel",
    "V Cvt Petrol",
    "V Cvt Diesel",
    "S Mt Diesel",
    "Vx Mt Diesel",
    "V Mt Diesel",
    "Vx Mt Petrol",
    "V Mt Petrol",
    "S Mt Petrol",
    "Exclusive Edition Diesel",
    "Exclusive Edition Petrol",
    "Vx Cvt Diesel",
    "Vx Cvt Petrol",
    "Ace Edition Cvt Diesel",
    "Ace Edition Cvt Petrol",
    "Ace Edition Mt Diesel",
    "Ace Edition Mt Petrol",
    "E Petrol",
    "S Petrol",
    "1.8 V Cvt",
    "1.8 Vx Cvt",
    "1.8 Zx Cvt",
    "1.6 Vx Mt",
    "1.6 Zx Mt",
    "Edge Plus Edition Diesel",
    "Edge Plus Edition Petrol",
    "2.0 At",
    "Sv Mt Petrol",
    "Sv Mt Diesel",
    "Zx Mt Diesel",
    "Zx Cvt Petrol",
    "Era Mt",
    "Magna Mt",
    "Magna Mt Cng",
    "Magna Amt",
    "Sportz Mt",
    "Sportz Mt Cng",
    "Sportz Amt",
    "Asta Mt",
    "Cng T + (Cng +",
    "T+",
    "Cng T (Cng +",
    "T+ Crdi",
    "T Crdi",
    "Era 1.2",
    "Era 1.4 Crdi",
    "Magna Plus",
    "Magna Plus Crdi",
    "Sportz Plus",
    "Sportz Plus Crdi Dual Tone",
    "Asta (O) 1.2",
    "Asta (O) Crdi",
    "Asta (O) Cvt",
    "Sportz Plus Dual Tone",
    "Sportz Plus Cvt",
    "Sportz Plus Crdi",
    "E 1.2 Petrol",
    "S 1.2 Petrol",
    "S 1.2 Amt Petrol",
    "Sx 1.2 Petrol",
    "Sx Plus 1.2 Amt Petrol",
    "Sx (O) 1.2 Petrol",
    "S 1.2 Cng Petrol (Cng +",
    "Sx Plus 1.0 Petrol",
    "S 1.2 Diesel",
    "S 1.2 Amt Diesel",
    "Sx Plus 1.2 Amt Diesel",
    "Sx (O) 1.2 Diesel",
    "Era T Crdi",
    "Era T+ Crdi",
    "Era T Vtvt",
    "Era T+ Vtvt",
    "Era T+ Cng Vtvt",
    "Era T Cng Vtvt",
    "1.2 Kappa Mt E",
    "1.0 Turbo Gdi Mt S",
    "1.4 Crdi Mt E",
    "1.0 Turbo Gdi Mt Sx",
    "1.0 Turbo Gdi Mt Sx Dual Tone",
    "1.0 Turbo Gdi Mt Sx(O)",
    "1.0 Turbo Gdi Dct S",
    "1.0 Turbo Gdi Dct Sx Plus",
    "1.2 Kappa Mt S",
    "1.4 Crdi Mt S",
    "1.4 Crdi Mt Sx",
    "1.4 Crdi Mt Sx Dual Tone",
    "1.4 Crdi Mt Sx(O)",
    "1.2 S",
    "1.2 Sx",
    "1.2 Sx Dual Tone",
    "1.4 Sx",
    "1.6 Vtvt Sx",
    "1.6 Crdi Sx",
    "1.6 Crdi Sx (O)",
    "1.6 Vtvt Sx (O)",
    "1.6 Crdi Sx Plus At",
    "1.6 Vtvt Sx(O) At",
    "1.4 Vtvt Ex",
    "1.4 Vtvt E",
    "1.6 Vtvt Sx (O) Anniversary Edition",
    "1.6 Vtvt Sx Plus At",
    "1.6 Crdi Sx(O) At",
    "1.4 Crdi E",
    "1.4 Crdi Ex",
    "1.2 Kappa Vtvt Magna",
    "1.2 Kappa Vtvt Sportz",
    "1.2 Kappa Vtvt Magna At",
    "1.2 Kappa Vtvt Sportz At",
    "1.2 Kappa Vtvt Sportz Dual Tone",
    "1.2 Kappa Vtvt Magna Cng",
    "Sx",
    "Sx At",
    "Sx(O) At",
    "2Wd Mt Diesel",
    "2Wd Mt Petrol",
    "2Wd At Gl Diesel",
    "2Wd At Gl Petrol",
    "4Wd At Gls Diesel",
    "2Wd At Gls Petrol",
    "2Wd At Gl(O) Petrol",
    "2Wd At Gl(O) Diesel",
    "Magna 1.2 Crdi",
    "Era 1.2 Vtvt",
    "Magna 1.2 Vtvt",
    "Magna Amt 1.2 Vtvt",
    "Sportz 1.2 Vtvt",
    "Sportz Amt 1.2 Vtvt",
    "Sportz Dual Tone 1.2 Vtvt",
    "Asta 1.2 Vtvt",
    "Sportz Amt 1.2 Crdi",
    "Asta 1.2 Crdi",
    "S 1.2",
    "S At 1.2",
    "Sx 1.2",
    "Sx 1.2 (O)",
    "S 1.2 Crdi",
    "E",
    "Sx 1.2 Crdi",
    "Sx 1.2 Crdi (O)",
    "E Crdi",
    "1.4 Crdi E Plus",
    "1.6 Vtvt E Plus",
    "1.6 Vtvt Sx At",
    "1.6 Vtvt Sx Dual Tone",
    "1.4 Crdi S",
    "1.6 Crdi Sx At",
    "1.6 Crdi Sx Dual Tone",
    "1.6 Crdi S At",
    "1.6 Vtvt Sx (O) Executive",
    "1.6 Crdi Sx (O) Executive",
    "1.6 Vtvt Ex",
    "Sports Edition Petrol",
    "Sports Edition Diesel",
    "Premium",
    "Ld Di Non Ac 9 Seater Bsiii",
    "Ld Crdfi Non Ac 9 Seater Bsiv",
    "Ld Di Ps Ac 9 Seater Bsiii",
    "Ld Crdfi Ps Ac 9 Seater Bsiii",
    "Sd Di 9 Seater Bsiii",
    "Ld Crdfi Ps Ac 9 Seater Bsiv",
    "Vd Crdfi 7 Seater Bsiii",
    "Vd Di 7 Seater Bsiii",
    "Sd Crdfi 9 Seater Bsiv",
    "Vd Crdfi 7 Seater Bsiv",
    "Sd Crdfi 9 Seater Bsiii",
    "4X2",
    "4X4",
    "High Z",
    "Z Prestige",
    "Se Diesel",
    "Se Petrol",
    "2.0 Prestige",
    "2.0 Portfolio",
    "2.0 Portfolio Diesel",
    "2.0 Prestige Diesel",
    "2.0 Pure Diesel",
    "3.0L",
    "3.0L Portfolio",
    "50",
    "Prestige",
    "Prestige Petrol",
    "5.0 Convertible R",
    "5.0 Coupe R",
    "Svr Coupe",
    "Svr Convertible",
    "2.0L Coupe",
    "2.0L Convertible",
    "2.0 Convertible R Dynamic",
    "2.0 Coupe R Dynamic",
    "2.0 Trailhawk 4X4 At",
    "2.0 Trailhawk (O) 4X4 At",
    "Limited",
    "Summit",
    "Srt",
    "Summit Petrol",
    "1.4 Limited At",
    "1.4 Sport",
    "1.4 Limited (O) At",
    "2.0 Sport",
    "2.0 Longitude",
    "2.0 Longitude (O)",
    "2.0 Limited",
    "2.0 Limited (O)",
    "2.0 Limited 4X4",
    "2.0 Limited (O) 4X4",
    "1.4 Limited Plus At Petrol",
    "2.0 Limited Plus 4X2 Diesel",
    "2.0 Limited Plus 4X4 Diesel",
    "2.0 Sport Plus",
    "1.4 Sport Plus",
    "1.4 Longitude (O) At",
    "1.4 Limited (O) At Petrol Black Pack",
    "2.0 Limited (O) Black Pack",
    "2.0 Limited (O) 4X4 Black Pack",
    "2.0 Limited Plus 4X4 At",
    "2.0 Longitude 4X4 At",
    "Unlimited",
    "Premium 7 Str",
    "Premium 8 Str",
    "Prestige 7 Str",
    "Prestige 9 (6+3) Str",
    "Limousine 7 Str",
    "Hte 1.5",
    "Htk 1.5",
    "Htk Plus 1.5",
    "Htx 1.5",
    "Htx Cvt 1.5",
    "Hte 1.5 Diesel",
    "Htk 1.5 Diesel",
    "Htk Plus 1.5 Diesel",
    "Htk Plus At 1.5 Diesel",
    "Htx Plus 1.5 Diesel",
    "Htx Plus At 1.5 Diesel",
    "Gtk 1.4",
    "Gtx 1.4",
    "Gtx At 1.4",
    "Gtx Plus 1.4",
    "Htx 1.5 Diesel",
    "Lp 610-4",
    "Lp 580-2",
    "Avio",
    "Performante",
    "Lp 580-2 Spyder",
    "Lp 610-4 Spyder",
    "Evo",
    "Evo Spyder",
    "Evo Rwd",
    "Lp 700-4",
    "Lp700-4 Roadster",
    "R-Dynamic Se",
    "3.0 Hse Diesel",
    "3.0 Se Diesel",
    "3.0 Hse Petrol",
    "3.0 Se Petrol",
    "3.0 S Diesel",
    "3.0 S Petrol",
    "3.0 Hse Luxury Diesel",
    "3.0 Hse Luxury Petrol",
    "Se R-Dynamic",
    "Se R-Dynamic Petrol",
    "2.0 Hse Dynamic",
    "2.0 Diesel R-Dynamic S",
    "2.0 Petrol R-Dynamic S",
    "5.0L V8 Svr Petrol",
    "2.0L S Petrol",
    "2.0L Se Petrol",
    "3.0L V6 Se Petrol",
    "2.0L Hse Petrol",
    "3.0L V6 Hse Petrol",
    "5.0L V8 Autobiography Dynamic Petrol",
    "3.0L Tdv6 S Diesel",
    "3.0L Tdv6 Se Diesel",
    "4.4L Sdv8 Hse Diesel",
    "5.0L V8 Autobiography Petrol",
    "5.0L V8 Svautobiography Dynamic Petrol",
    "3.0L V6 Vogue Lwb Petrol",
    "5.0L V8 Svautobiography Lwb Petrol",
    "3.0L Tdv6 Vogue Diesel",
    "3.0L Tdv6 Vogue Lwb Diesel",
    "4.4L Sdv8 Autobiography Lwb Diesel",
    "4.4L Sdv8 Svautobiography Lwb Diesel",
    "4.4L Sdv8 Vogue Se Lwb Diesel",
    "3.0L V6 Vogue Se Lwb Petrol",
    "450Hl Luxury",
    "300H",
    "F-Sport",
    "Luxury",
    "Ultra Luxury",
    "Distinct",
    "D2",
    "D4",
    "D6",
    "2Wd At",
    "4Wd At",
    "K2 6Str",
    "K2+ 6Str",
    "K2 D 6Str",
    "K2+ D 6Str",
    "K4+ D 6Str",
    "K4+ 6Str",
    "K6+ 6Str",
    "K6+ D 6Str",
    "K8 6Str",
    "K8 D 6Str",
    "K8 6 Str Dual Tone",
    "K8 D 6 Str Dual Tone",
    "K4+ 5Str",
    "K6+ 5Str",
    "K8 5Str",
    "K4+ D 5Str",
    "K6+ D 5Str",
    "K8 D 5Str",
    "K2 D 5Str Taxi",
    "K2 D 6Str Taxi",
    "K2 5Str Cng Taxi",
    "K2 6Str Cng Taxi",
    "Zlx",
    "Slx",
    "Sle",
    "Lx",
    "Plus Ac Bs4 Ps",
    "Plus Non Ac Bs4 Ps",
    "1.2 W4",
    "1.2 W6",
    "1.2 W8",
    "1.2 W8(O)",
    "1.5 W4",
    "1.5 W6",
    "1.5 W8",
    "1.5 W8 (O)",
    "1.5 W8 Amt",
    "1.5 W8 (O) Amt",
    "1.5 W6 Amt",
    "P4",
    "P6",
    "Crde",
    "700 Special Edition",
    "Crde Abs",
    "P8",
    "M2 7 Str",
    "M4 7 Str",
    "M6 7 Str",
    "M8 7 Str",
    "M2 8 Str",
    "M4 8 Str",
    "M6 8 Str",
    "M8 8 Str",
    "S3 2Wd",
    "4Wd Getaway",
    "2Wd Getaway",
    "S5 2Wd",
    "S7 120 2Wd",
    "S7 140 2Wd",
    "S11 2Wd",
    "S11 4Wd",
    "S9 2Wd",
    "G At",
    "W7",
    "W7 At",
    "W9",
    "W9 At",
    "W11",
    "W11 At",
    "W11 (O)",
    "W11 (O) At",
    "W11 (O) Awd",
    "W11 (O) Awd At",
    "W3",
    "T4 Plus",
    "T6 Plus",
    "T8",
    "T10",
    "T10 (O)",
    "T10 Dual Tone",
    "T10 (O) Dual Tone",
    "D2 Bs-Iv",
    "D4 Bs-Iv",
    "H4 Bs-Iv",
    "H4 Abs Bs-Iv",
    "H8 Abs Airbags Bs-Iv",
    "Ex",
    "Ex Non Ac",
    "N4",
    "N6",
    "N8",
    "N4 +",
    "N6 Amt",
    "N8 Amt",
    "1.5 D2",
    "1.5 D4 Bs-Iv",
    "1.5 D6 Bs-Iv",
    "5 Str",
    "7 Str",
    "5 Str With Ac+Htr",
    "5 Str With Ac+Htr Cng",
    "5 Str With Htr Cng",
    "Lxi",
    "Vxi",
    "Vxi (O)",
    "Lxi Cng (O)",
    "Vxi Amt (O)",
    "H2",
    "H2 Cng",
    "Vxi Amt",
    "Zxi",
    "Zxi (O)",
    "Zxi Amt",
    "Zxi Amt (O)",
    "Alpha 1.2 Amt",
    "Alpha 1.2 Mt",
    "Delta 1.2 Amt",
    "Delta 1.2 Mt",
    "Sigma 1.2 Mt",
    "Zeta 1.2 Amt",
    "Zeta 1.2 Mt",
    "Ldi",
    "Lxi Cng",
    "Vdi",
    "Zdi Amt",
    "Zdi",
    "Zxi Plus",
    "Zxi At",
    "Zxi Plus Amt",
    "Zdi Plus",
    "Vdi Amt",
    "Zdi Plus Amt",
    "Std (O)",
    "Lxi (O)",
    "Lxi Cng (Cng +",
    "Lxi (O) Cng (Cng +",
    "Vxi Plus",
    "Vxi Ags",
    "Vxi+",
    "Vxi (O) Ags",
    "Vxi+ Ags",
    "Vxi At",
    "Zxi (Opt)",
    "Vxi Cng Mt",
    "Zxi Ags",
    "Lxi Mt (O)",
    "Vxi (O) Mt",
    "Zxi (O) Ags",
    "Hard Top",
    "Soft Top",
    "Zdi+",
    "Zdi+ Dual Tone",
    "Zdi+ Ags",
    "Vdi Ags",
    "Zdi Ags",
    "Zdi+ Dual Tone Ags",
    "Zeta Mt",
    "Alpha Mt",
    "Zeta At",
    "Alpha At",
    "5 Str Bs-Iv",
    "E 8 Str Bs-Iv",
    "1.3 Delta",
    "1.3 Alpha",
    "1.3 Sigma",
    "1.3 Zeta",
    "1.2 Alpha",
    "1.2 Alpha Cvt",
    "1.2 Delta",
    "1.2 Delta Cvt",
    "1.2 Sigma",
    "1.2 Zeta",
    "1.2 Delta Dualjet",
    "1.2 Zeta Dualjet",
    "1.2 Zeta Cvt",
    "1.5L Vdi",
    "1.5L Zdi",
    "1.5L Zdi Plus",
    "Vxi Cng (Cng +",
    "Rs 1.0",
    "1.3L Sigma",
    "1.3L Delta",
    "1.3L Zeta",
    "1.3L Alpha",
    "H1",
    "H1 (O)",
    "1.3L Alpha Smart Hybrid",
    "1.3L Sigma Smart Hybrid",
    "1.3L Delta Smart Hybrid",
    "1.3L Zeta Smart Hybrid",
    "1.5L Sigma Smart Hybrid",
    "1.5L Delta Smart Hybrid",
    "1.5L Zeta Smart Hybrid",
    "1.5L Alpha Smart Hybrid",
    "1.5L Delta At Smart Hybrid",
    "1.5L Zeta At Smart Hybrid",
    "1.5L Alpha At Smart Hybrid",
    "1.5L Alpha",
    "1.5L Delta",
    "1.5L Zeta",
    "1.2L Zxi",
    "1.2L Vxi",
    "1.2L Vxi Ags",
    "1.2L Zxi Ags",
    "1.2L Vxi (O)",
    "1.2L Vxi Ags (O)",
    "Vxi Ags (O)",
    "Lxi (O) Cng",
    "Diesel",
    "Gransport",
    "Granlusson",
    "Granlusso",
    "Excite",
    "Exclusive",
    "1.5L Style",
    "2.0L Style",
    "2.0L Super",
    "2.0L Smart",
    "2.0L Sharp",
    "1.5L Super",
    "1.5L Super Hybrid",
    "1.5L Sharp Hybrid",
    "1.5L Smart Hybrid",
    "1.5L Smart Dct",
    "1.5L Sharp Dct",
    "Cooper D",
    "Cooper S",
    "Hatch",
    "Cooper Sd",
    "Cooper S Jcw Inspired",
    "Black Edition",
    "2.4L Outlander",
    "2.5 Mt",
    "2.5 At",
    "Limited Edition",
    "Select Plus Mt",
    "Select Plus At",
    "3.2 At",
    "Xl",
    "Xv",
    "Xl (O)",
    "Xe Petrol",
    "Xl Petrol",
    "Xl Diesel",
    "Xv Diesel",
    "Xe Diesel",
    "Xv Cvt",
    "Special Edition Diesel",
    "Xe D 85Ps",
    "Xv D Premium 110 Ps Amt",
    "Xl (P)",
    "Xl D(O)",
    "Xv D Premium 110 Ps",
    "Sport Edition",
    "3.8 V6",
    "Xl (O) Cvt",
    "Xld (O)",
    "Xvd",
    "Xv Petrol",
    "Xv Premium",
    "Xv Premium (O)",
    "Xv Premium (O) Dual Tone",
    "Boxster",
    "Cayman",
    "Turbo",
    "Turbo Executive",
    "Turbo Sport Turismo",
    "E-Hybrid",
    "Base",
    "Carrera S",
    "Carrera S Cabriolet",
    "Gx",
    "Glx",
    "Dx",
    "Crdi4",
    "Rxe 0.8",
    "Std 0.8",
    "Rxl 0.8",
    "Rxt 0.8",
    "Rxt 1.0",
    "Climber 1.0 Mt",
    "Rxt Amt 1.0",
    "Climber Amt 1.0",
    "Rxt (O) 1.0",
    "Rxt (O) Amt 1.0",
    "Climber (O) Mt 1.0",
    "Climber (O) Amt 1.0",
    "Rxe",
    "Rxl",
    "Rxt",
    "Rxz",
    "Rxe Petrol",
    "Rxs Petrol",
    "Rxs (Opt) Cvt",
    "85 Ps Rxe Mt Diesel",
    "85 Ps Rxs Mt Diesel",
    "110 Ps Rxs Mt Diesel",
    "110 Ps Rxz Mt Diesel",
    "110 Ps Rxz Amt Diesel",
    "110 Ps Rxs Awd (Opt) Diesel",
    "85 Ps Std",
    "85 Ps Rxe 8 Seater",
    "Stepway Rxz 110Ps 8-Seater",
    "Stepway Rxz 110Ps 7-Seater",
    "Stepway Rxl 85Ps 8-Seater",
    "Stepway Rxz 85Ps 8-Seater",
    "85 Ps Rxe 7 Seater",
    "Rxe Diesel",
    "Platine Diesel Dual Tone",
    "Platine Petrol Dual Tone",
    "Sportline 1.8L Tsi At",
    "Sportline 2.0L Tdi At",
    "Style 2.0 Tdi 4X4 At",
    "Laurin And Klement",
    "Corporate Edition",
    "Monte Carlo 1.5 Tdi At",
    "Monte Carlo 1.6 Mpi At",
    "Monte Carlo 1.5 Tdi Mt",
    "Monte Carlo 1.6 Mpi Mt",
    "Style 1.8 Tsi Mt",
    "Style 1.8 Tsi At",
    "L & K 1.8 Tsi At",
    "L & K 2.0 Tdi At",
    "Style 2.0 Tdi At",
    "Corporate Edition 1.8 Tsi At",
    "Corporate Edition 2.0 Tdi At",
    "2.0 Tdi At",
    "1.6 Mpi Ambition",
    "1.5 Tdi Cr Active",
    "1.6 Mpi Active",
    "1.5 Tdi Cr Ambition",
    "1.5 Tdi Cr Ambition At",
    "1.6 Mpi Style At",
    "1.5 Tdi Cr Style At",
    "1.5 Tdi Cr Style",
    "1.6 Mpi Style",
    "1.6 Mpi Ambition At",
    "Onyx Mt Petrol",
    "Onyx At Petrol",
    "Onyx Mt Diesel",
    "Onyx At Diesel",
    "Ambition 1.4 Tsi",
    "Ambition 2.0 Tdi Cr",
    "Style 1.4 Tsi",
    "Style 2.0 Tdi Cr",
    "Style 2.0 Tdi Cr At",
    "L & K 2.0 Tdi Cr At",
    "Corporate Edition 1.4 Tsi",
    "Corporate Edition 2.0 Tdi",
    "Onyx 1.8 Tsi Dsg",
    "Onyx 2.0 Tdi Dsg",
    "Xt",
    "Xe",
    "Emax Xm",
    "Xta",
    "Xm",
    "Xma",
    "Revotron Xe",
    "Revotron Xt",
    "Revotron Xz",
    "Revotron Xz Plus",
    "Revotron Xz Plus Dual Tone",
    "Revotron Xza",
    "Revotron Xza Plus",
    "Revotron Xza Plus Dual Tone",
    "Xt Diesel",
    "Xm Diesel",
    "Xms Diesel",
    "Xt Petrol",
    "Xm Petrol",
    "Xms Petrol",
    "Xz Petrol",
    "Xz (O) Petrol",
    "Xz Diesel",
    "Xz (O) Diesel",
    "Revotron Xm",
    "Revotron Xma",
    "Xma Diesel",
    "Xta Diesel",
    "Zest Premio Edition",
    "Xz",
    "Xz Plus",
    "Xz Plus Dual Tone",
    "Xz Plus (O)",
    "Xz Plus (O) Dual Tone",
    "Xza Plus",
    "Xza Plus Dual Tone",
    "Xza Plus (O)",
    "Xza Plus (O) Dual Tone",
    "Xz Plus Diesel",
    "Xz Plus Diesel Dual Tone",
    "Xz Plus (O) Diesel",
    "Xz Plus (O) Diesel Dual Tone",
    "Xza Plus Diesel",
    "Xza Plus Diesel Dual Tone",
    "Xza Plus (O) Diesel",
    "Xza Plus (O) Diesel Dual Tone",
    "Xm+",
    "Xt+",
    "Xe+",
    "Xm Plus 4X2",
    "Xt 4X4",
    "Xta 4X2",
    "Xt 4X2",
    "Xe 4X2",
    "Xm 4X2",
    "Xma 4X2",
    "2.2 Lx 4X2",
    "2.2 Ex 4X2",
    "2.2 Vx 4X2 Varicor 400",
    "2.2 Vx 4X4 Varicor 400",
    "Xz Plus Lux",
    "Revotorq Xe",
    "Revotorq Xm",
    "Revotorq Xt",
    "Revotorq Xz",
    "Revotorq Xz Dual Tone",
    "Revotorq Dark Edition",
    "1.2L Revotron",
    "1.05L Revotorq",
    "1.2L Revotron Amt",
    "15S",
    "G",
    "V",
    "Gd",
    "Vx",
    "Vxd",
    "Vd",
    "Dual Tone V",
    "Dual Tone Vd",
    "Dual Tone Vx",
    "Dual Tone Vxd",
    "Gxd",
    "Vx Dual Tone Limited Edition",
    "Vxd Dual Tone Limited Edition",
    "Vxd Limited Edition",
    "Vx Limited Edition",
    "1.2 X Edition",
    "1.4 X Edition",
    "G Hybrid",
    "G Cvt",
    "G Mt",
    "Vx L",
    "2.4 Gx 7 Str",
    "2.4 Vx 7 Str",
    "2.4 Gx 8 Str",
    "2.4 Vx 8 Str",
    "2.4 Zx 7 Str",
    "2.7 Gx At 8 Str",
    "2.7 Gx At 7 Str",
    "2.7 Zx At 7 Str",
    "2.7 Vx 7 Str",
    "2.7 Gx Mt 7 Str",
    "2.7 Gx Mt 8 Str",
    "Touring Sport 2.4 Vx 7 Str",
    "Touring Sport 2.7 Vx 7 Str",
    "Touring Sport 2.7 Zx At 7 Str",
    "2.4 G Plus 7 Str",
    "2.4 G Plus 8 Str",
    "G Petrol",
    "G At Petrol",
    "Gl Petrol",
    "Gl Diesel",
    "G Diesel",
    "Vl At Petrol",
    "2.8 4X2 At",
    "2.8 4X2 Mt",
    "2.8 4X4 Mt",
    "2.8 4X4 At",
    "2.7 4X2 At",
    "2.7 4X2 Mt",
    "Trd Celebratory Edition",
    "Z8",
    "Hybrid",
    "J",
    "J Cvt",
    "V (O)",
    "J (O)",
    "G (O)",
    "J (O) Cvt",
    "G (O) Cvt",
    "V (O) Cvt",
    "Trendline 1.0L (P)",
    "Comfortline 1.0 (P)",
    "Highline Plus 1.0 (P)",
    "Trendline 1.5L (D)",
    "Comfortline 1.5 (D)",
    "Highline Plus 1.5 (D)",
    "Gt Tsi",
    "Gt Tdi",
    "Trendline 1.5L Tdi",
    "Comfortline 1.5L Tdi",
    "Highline Plus 1.5L Tdi Dsg",
    "Highline Plus 1.5L Tdi",
    "Trendline 1.0L",
    "Comfortline 1.0L",
    "Highline Plus 1.0L",
    "Gt Line Tdi Dsg",
    "Comfortline 2.0L Tdi Amt",
    "Highline 2.0L Tdi Amt",
    "Trendline 1.6 (P)",
    "Highline 1.6 (P)",
    "Comfortline 1.6 (P)",
    "Highline 1.2 (P) Dsg",
    "Highline Plus 1.2 (P) Dsg",
    "Trendline 1.5 (D)",
    "Highline 1.5 (D)",
    "Highline 1.5 (D) Dsg",
    "Highline Plus 1.5 (D) Dsg",
    "Gt Line (D)",
    "Gt Line (P) Dsg",
    "2.0 Tdi Comfortline",
    "2.0 Tdi Highline",
    "2.0 Tdi Comfortline Connect",
    "2.0 Tdi Highline Connect",
    "D4 Momentum",
    "D4 Inscription",
    "T4 R-Design",
    "Kinetic",
    "R Design",
    "Polestar",
    "Momentum",
    "Inscription D5",
    "D5 Inscription",
    "D5 Momentum",
    "T8 Excellence",
    "T8 Inscription",
    "D5 R-Design",
    "D3",
    "T4",
    "B 180 Sport",
    "B 200 Cdi Sport",
    "B 180 Night Edition",
    "B 200 Cdi Night Edition",
    "200 Sport",
    "200 Cdi Style",
    "200 D Sport",
    "E400",
    "350 Cdi",
    "63 Amg",
    "400 4Matic",
    "Grand Edition Petrol",
    "Grand Edition Diesel",
    "S 350 D",
    "S 450",
    "Amg S 63 Coupe",
    "Amg G 63",
    "G 350D",
    "S650",
    "S560",
    "S500",
    "6.6",
    "Ewb",
    "Suv",
    "6.8 L",
    "E200",
    "E350 D",
    "E220D",
    "E 63 S Amg",
    "E200 Expression",
    "E200 Exclusive",
    "E220D Expression",
    "E220D Exclusive",
    "C300",
    "Expression Elwb",
    "Exclusive Lwb",
    "Elite",
    "E 220D",
    "R",
    "Roadster",
    "63 S 4Matic+",
    "Convertible",
    "Phantom",
    "Datsun D",
    "Datsun T",
    "Datsun T (O)",
    "Datsun A (O)",
    "Datsun A",
    "Datsun T Vdc",
    "Datsun T (O) Vdc",
    "Datsun T Cvt",
    "Datsun T (O) Cvt",
    "180",
    "200D",
    "C 220D Prime",
    "C 220D Progressive",
    "C 300D Amg Line",
    "C 43 Amg",
    "C 200 Prime",
    "C 200 Progressive",
    "300D 4Matic",
    "400D 4Matic Hip Hop Edition",
    "300D",
    "200 D Style",
    "45 Amg 4Matic",
    "220 D 4Matic",
    "45 Aero Edition",
    "200 Progressive",
    "220D 4Matic Progressive"
    ];
    $( "#abc2" ).autocomplete({
      source: availableTags
    });
  } );